allprojects {
    repositories {
        google()
        mavenCentral()

        // INFO: Required for background_fetch plugin
        maven {
            url "${project(':background_fetch').projectDir}/libs"
        }
    }
}

subprojects {
    afterEvaluate { project ->
        if (project.hasProperty('android')) {
            project.android {
                if (!hasProperty('namespace') || namespace == null || namespace.isEmpty()) {
                    // Assign a default namespace based on the project name or group
                    namespace = project.group.toString() ?: "uk.co.tdsstudios.${project.name}"
                }
            }
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
