name: noterly
description: Simple notification reminders.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  intl: ^0.19.0
  uuid: ^4.5.2
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  google_fonts: ^6.3.0
  dynamic_color: ^1.6.3
  jiffy: ^6.0.0
  background_fetch: ^1.4.0
  quick_actions: ^1.0.1
  url_launcher: ^6.1.8
  logger: ^2.6.2
  flutter_localizations:
    sdk: flutter
  auto_size_text: ^3.0.0
  fluttertoast: ^9.0.0
  receive_sharing_intent:
    git:
      url: https://github.com/KasemJaffer/receive_sharing_intent
  receive_intent: ^0.2.3
  dots_indicator: ^4.0.1
  flutter_translate: ^4.0.4
  system_settings_2: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  intl: ^0.20.2

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/google_fonts/
